# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlPoint-XML-XHTML
version:      0.02
version_from: 
installdirs:  site
requires:
    Memoize:                       1
    PerlPoint::Generator::XML:     0.01
    Test::Harness:                 1.25
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
